[project]
name = "helpbot"
version = "1"
description = "QA chatbot using FastAPI and Streamlit"

dependencies = [
    "aiosqlite>=0.21.0",
    "asyncpg>=0.29.0",
    "extra-streamlit-components>=0.1.80",
    "fastapi>=0.115.12",
    "langchain>=0.3.24",
    "langchain-community>=0.3.23",
    "langchain-core>=0.3.56",
    "langchain-huggingface>=0.1.2",
    "langchain-ollama>=0.3.2",
    "more-itertools>=10.7.0",
    "pydantic>=2.11.4",
    "qdrant-client>=1.8.0",
    "requests>=2.32.3",
    "sentence-transformers>=4.1.0",
    "sqlalchemy>=2.0.40",
    "streamlit>=1.45.0",
    "torch>=2.7.0",
    "uvicorn>=0.34.2",
]

[project.optional-dependencies]
dev = ["ruff", "mypy"]
